import monstera from "../assets/monstera.jpg";

export const plantList = [
	{
		name: "monstera",
		category: "classique",
		id: "1ed",
		isBestSale: true,
		light: 2,
		water: 3,
		cover: monstera,
		size: 5,
		color: "red",
		isSpecialOffer: true,
	},
	{
		name: "ficus lyrata",
		category: "classique",
		id: "2ab",
		light: 3,
		water: 1,
		cover: monstera,
		size: 4,
		color: "blue",
		isSpecialOffer: true,
	},
	{
		name: "pothos argenté",
		category: "classique",
		id: "3sd",
		light: 1,
		water: 2,
		cover: monstera,
		size: 3,
		color: "red",
		isSpecialOffer: false,
	},
	{
		name: "yucca",
		category: "classique",
		id: "4kk",
		light: 3,
		water: 1,
		cover: monstera,
		size: 4,
		color: "yellow",
		isSpecialOffer: true,
	},
	{
		name: "olivier",
		category: "extérieur",
		id: "5pl",
		light: 3,
		water: 1,
		cover: monstera,
		size: 5,
		color: "yellow",
		isSpecialOffer: false,
	},
	{
		name: "géranium",
		category: "extérieur",
		id: "6uo",
		light: 2,
		water: 2,
		cover: monstera,
		size: 3,
		color: "red",
		isSpecialOffer: false,
	},
	{
		name: "basilique",
		category: "extérieur",
		id: "7ie",
		isBestSale: true,
		light: 2,
		water: 3,
		cover: monstera,
		size: 1,
		color: "blue",
		isSpecialOffer: true,
	},
	{
		name: "aloe",
		category: "plante grasse",
		id: "8fp",
		light: 2,
		water: 1,
		cover: monstera,
		size: 2,
		color: "blue",
		isSpecialOffer: false,
	},
	{
		name: "succulente",
		category: "plante grasse",
		id: "9vn",
		light: 2,
		water: 1,
		cover: monstera,
		size: 1,
		color: "red",
		isSpecialOffer: false,
	},
];
